# Generated by Django 3.0.4 on 2020-09-01 20:34

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=20)),
                ('Title', models.CharField(default='N/A', max_length=100)),
                ('Year', models.CharField(default='N/A', max_length=10)),
                ('Rated', models.CharField(default='N/A', max_length=10)),
                ('Released', models.CharField(default='N/A', max_length=20)),
                ('Runtime', models.CharField(default='N/A', max_length=20)),
                ('Genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('Director', models.CharField(default='N/A', max_length=50)),
                ('Writers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('Actors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('Plot', models.TextField(default='N/A')),
                ('Language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('Country', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('Awards', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('Poster', models.URLField(null=True)),
                ('Ratings', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=list, size=None)),
                ('Metascore', models.IntegerField(null=True)),
                ('imdbID', models.CharField(max_length=20)),
                ('Type', models.CharField(default='N/A', max_length=20)),
                ('DVD', models.CharField(default='N/A', max_length=20)),
                ('BoxOffice', models.CharField(default='N/A', max_length=20)),
                ('Production', models.CharField(default='N/A', max_length=20)),
                ('Website', models.URLField(null=True)),
                ('Response', models.BooleanField(default=True)),
            ],
        ),
    ]
